#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADefWebserver.Modules.ADefHelpDesk
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="ADefHelpDeskStandAlone")]
	public partial class dnnHelpDeskDALDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADefHelpDesk_Attachment(ADefHelpDesk_Attachment instance);
    partial void UpdateADefHelpDesk_Attachment(ADefHelpDesk_Attachment instance);
    partial void DeleteADefHelpDesk_Attachment(ADefHelpDesk_Attachment instance);
    partial void InsertADefHelpDesk_Version(ADefHelpDesk_Version instance);
    partial void UpdateADefHelpDesk_Version(ADefHelpDesk_Version instance);
    partial void DeleteADefHelpDesk_Version(ADefHelpDesk_Version instance);
    partial void InsertADefHelpDesk_Category(ADefHelpDesk_Category instance);
    partial void UpdateADefHelpDesk_Category(ADefHelpDesk_Category instance);
    partial void DeleteADefHelpDesk_Category(ADefHelpDesk_Category instance);
    partial void InsertADefHelpDesk_LastSearch(ADefHelpDesk_LastSearch instance);
    partial void UpdateADefHelpDesk_LastSearch(ADefHelpDesk_LastSearch instance);
    partial void DeleteADefHelpDesk_LastSearch(ADefHelpDesk_LastSearch instance);
    partial void InsertADefHelpDesk_Log(ADefHelpDesk_Log instance);
    partial void UpdateADefHelpDesk_Log(ADefHelpDesk_Log instance);
    partial void DeleteADefHelpDesk_Log(ADefHelpDesk_Log instance);
    partial void InsertADefHelpDesk_Role(ADefHelpDesk_Role instance);
    partial void UpdateADefHelpDesk_Role(ADefHelpDesk_Role instance);
    partial void DeleteADefHelpDesk_Role(ADefHelpDesk_Role instance);
    partial void InsertADefHelpDesk_Setting(ADefHelpDesk_Setting instance);
    partial void UpdateADefHelpDesk_Setting(ADefHelpDesk_Setting instance);
    partial void DeleteADefHelpDesk_Setting(ADefHelpDesk_Setting instance);
    partial void InsertADefHelpDesk_TaskAssociation(ADefHelpDesk_TaskAssociation instance);
    partial void UpdateADefHelpDesk_TaskAssociation(ADefHelpDesk_TaskAssociation instance);
    partial void DeleteADefHelpDesk_TaskAssociation(ADefHelpDesk_TaskAssociation instance);
    partial void InsertADefHelpDesk_TaskCategory(ADefHelpDesk_TaskCategory instance);
    partial void UpdateADefHelpDesk_TaskCategory(ADefHelpDesk_TaskCategory instance);
    partial void DeleteADefHelpDesk_TaskCategory(ADefHelpDesk_TaskCategory instance);
    partial void InsertADefHelpDesk_TaskDetail(ADefHelpDesk_TaskDetail instance);
    partial void UpdateADefHelpDesk_TaskDetail(ADefHelpDesk_TaskDetail instance);
    partial void DeleteADefHelpDesk_TaskDetail(ADefHelpDesk_TaskDetail instance);
    partial void InsertADefHelpDesk_Task(ADefHelpDesk_Task instance);
    partial void UpdateADefHelpDesk_Task(ADefHelpDesk_Task instance);
    partial void DeleteADefHelpDesk_Task(ADefHelpDesk_Task instance);
    partial void InsertADefHelpDesk_UserRole(ADefHelpDesk_UserRole instance);
    partial void UpdateADefHelpDesk_UserRole(ADefHelpDesk_UserRole instance);
    partial void DeleteADefHelpDesk_UserRole(ADefHelpDesk_UserRole instance);
    partial void InsertADefHelpDesk_User(ADefHelpDesk_User instance);
    partial void UpdateADefHelpDesk_User(ADefHelpDesk_User instance);
    partial void DeleteADefHelpDesk_User(ADefHelpDesk_User instance);
    #endregion
		
		public dnnHelpDeskDALDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dnnHelpDeskDALDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dnnHelpDeskDALDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dnnHelpDeskDALDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dnnHelpDeskDALDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_Attachment> ADefHelpDesk_Attachments
		{
			get
			{
				return this.GetTable<ADefHelpDesk_Attachment>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_Version> ADefHelpDesk_Versions
		{
			get
			{
				return this.GetTable<ADefHelpDesk_Version>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_Category> ADefHelpDesk_Categories
		{
			get
			{
				return this.GetTable<ADefHelpDesk_Category>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_LastSearch> ADefHelpDesk_LastSearches
		{
			get
			{
				return this.GetTable<ADefHelpDesk_LastSearch>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_Log> ADefHelpDesk_Logs
		{
			get
			{
				return this.GetTable<ADefHelpDesk_Log>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_Role> ADefHelpDesk_Roles
		{
			get
			{
				return this.GetTable<ADefHelpDesk_Role>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_Setting> ADefHelpDesk_Settings
		{
			get
			{
				return this.GetTable<ADefHelpDesk_Setting>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_TaskAssociation> ADefHelpDesk_TaskAssociations
		{
			get
			{
				return this.GetTable<ADefHelpDesk_TaskAssociation>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_TaskCategory> ADefHelpDesk_TaskCategories
		{
			get
			{
				return this.GetTable<ADefHelpDesk_TaskCategory>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_TaskDetail> ADefHelpDesk_TaskDetails
		{
			get
			{
				return this.GetTable<ADefHelpDesk_TaskDetail>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_Task> ADefHelpDesk_Tasks
		{
			get
			{
				return this.GetTable<ADefHelpDesk_Task>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_UserRole> ADefHelpDesk_UserRoles
		{
			get
			{
				return this.GetTable<ADefHelpDesk_UserRole>();
			}
		}
		
		public System.Data.Linq.Table<ADefHelpDesk_User> ADefHelpDesk_Users
		{
			get
			{
				return this.GetTable<ADefHelpDesk_User>();
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_Attachments")]
	public partial class ADefHelpDesk_Attachment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AttachmentID;
		
		private int _DetailID;
		
		private string _AttachmentPath;
		
		private string _FileName;
		
		private string _OriginalFileName;
		
		private int _UserID;
		
		private EntityRef<ADefHelpDesk_TaskDetail> _ADefHelpDesk_TaskDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAttachmentIDChanging(int value);
    partial void OnAttachmentIDChanged();
    partial void OnDetailIDChanging(int value);
    partial void OnDetailIDChanged();
    partial void OnAttachmentPathChanging(string value);
    partial void OnAttachmentPathChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnOriginalFileNameChanging(string value);
    partial void OnOriginalFileNameChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public ADefHelpDesk_Attachment()
		{
			this._ADefHelpDesk_TaskDetail = default(EntityRef<ADefHelpDesk_TaskDetail>);
			OnCreated();
		}
		
		[Column(Storage="_AttachmentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AttachmentID
		{
			get
			{
				return this._AttachmentID;
			}
			set
			{
				if ((this._AttachmentID != value))
				{
					this.OnAttachmentIDChanging(value);
					this.SendPropertyChanging();
					this._AttachmentID = value;
					this.SendPropertyChanged("AttachmentID");
					this.OnAttachmentIDChanged();
				}
			}
		}
		
		[Column(Storage="_DetailID", DbType="Int NOT NULL")]
		public int DetailID
		{
			get
			{
				return this._DetailID;
			}
			set
			{
				if ((this._DetailID != value))
				{
					if (this._ADefHelpDesk_TaskDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDetailIDChanging(value);
					this.SendPropertyChanging();
					this._DetailID = value;
					this.SendPropertyChanged("DetailID");
					this.OnDetailIDChanged();
				}
			}
		}
		
		[Column(Storage="_AttachmentPath", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string AttachmentPath
		{
			get
			{
				return this._AttachmentPath;
			}
			set
			{
				if ((this._AttachmentPath != value))
				{
					this.OnAttachmentPathChanging(value);
					this.SendPropertyChanging();
					this._AttachmentPath = value;
					this.SendPropertyChanged("AttachmentPath");
					this.OnAttachmentPathChanged();
				}
			}
		}
		
		[Column(Storage="_FileName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[Column(Storage="_OriginalFileName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string OriginalFileName
		{
			get
			{
				return this._OriginalFileName;
			}
			set
			{
				if ((this._OriginalFileName != value))
				{
					this.OnOriginalFileNameChanging(value);
					this.SendPropertyChanging();
					this._OriginalFileName = value;
					this.SendPropertyChanged("OriginalFileName");
					this.OnOriginalFileNameChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_TaskDetail_ADefHelpDesk_Attachment", Storage="_ADefHelpDesk_TaskDetail", ThisKey="DetailID", OtherKey="DetailID", IsForeignKey=true)]
		public ADefHelpDesk_TaskDetail ADefHelpDesk_TaskDetail
		{
			get
			{
				return this._ADefHelpDesk_TaskDetail.Entity;
			}
			set
			{
				ADefHelpDesk_TaskDetail previousValue = this._ADefHelpDesk_TaskDetail.Entity;
				if (((previousValue != value) 
							|| (this._ADefHelpDesk_TaskDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADefHelpDesk_TaskDetail.Entity = null;
						previousValue.ADefHelpDesk_Attachments.Remove(this);
					}
					this._ADefHelpDesk_TaskDetail.Entity = value;
					if ((value != null))
					{
						value.ADefHelpDesk_Attachments.Add(this);
						this._DetailID = value.DetailID;
					}
					else
					{
						this._DetailID = default(int);
					}
					this.SendPropertyChanged("ADefHelpDesk_TaskDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_Version")]
	public partial class ADefHelpDesk_Version : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _VersionNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVersionNumberChanging(string value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public ADefHelpDesk_Version()
		{
			OnCreated();
		}
		
		[Column(Storage="_VersionNumber", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_Categories")]
	public partial class ADefHelpDesk_Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoryID;
		
		private int _PortalID;
		
		private System.Nullable<int> _ParentCategoryID;
		
		private string _CategoryName;
		
		private int _Level;
		
		private bool _RequestorVisible;
		
		private bool _Selectable;
		
		private EntitySet<ADefHelpDesk_TaskCategory> _ADefHelpDesk_TaskCategories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIDChanging(int value);
    partial void OnCategoryIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnParentCategoryIDChanging(System.Nullable<int> value);
    partial void OnParentCategoryIDChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    partial void OnRequestorVisibleChanging(bool value);
    partial void OnRequestorVisibleChanged();
    partial void OnSelectableChanging(bool value);
    partial void OnSelectableChanged();
    #endregion
		
		public ADefHelpDesk_Category()
		{
			this._ADefHelpDesk_TaskCategories = new EntitySet<ADefHelpDesk_TaskCategory>(new Action<ADefHelpDesk_TaskCategory>(this.attach_ADefHelpDesk_TaskCategories), new Action<ADefHelpDesk_TaskCategory>(this.detach_ADefHelpDesk_TaskCategories));
			OnCreated();
		}
		
		[Column(Storage="_CategoryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_ParentCategoryID", DbType="Int")]
		public System.Nullable<int> ParentCategoryID
		{
			get
			{
				return this._ParentCategoryID;
			}
			set
			{
				if ((this._ParentCategoryID != value))
				{
					this.OnParentCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._ParentCategoryID = value;
					this.SendPropertyChanged("ParentCategoryID");
					this.OnParentCategoryIDChanged();
				}
			}
		}
		
		[Column(Storage="_CategoryName", DbType="NVarChar(50)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		[Column(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[Column(Storage="_RequestorVisible", DbType="Bit NOT NULL")]
		public bool RequestorVisible
		{
			get
			{
				return this._RequestorVisible;
			}
			set
			{
				if ((this._RequestorVisible != value))
				{
					this.OnRequestorVisibleChanging(value);
					this.SendPropertyChanging();
					this._RequestorVisible = value;
					this.SendPropertyChanged("RequestorVisible");
					this.OnRequestorVisibleChanged();
				}
			}
		}
		
		[Column(Storage="_Selectable", DbType="Bit NOT NULL")]
		public bool Selectable
		{
			get
			{
				return this._Selectable;
			}
			set
			{
				if ((this._Selectable != value))
				{
					this.OnSelectableChanging(value);
					this.SendPropertyChanging();
					this._Selectable = value;
					this.SendPropertyChanged("Selectable");
					this.OnSelectableChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_Category_ADefHelpDesk_TaskCategory", Storage="_ADefHelpDesk_TaskCategories", ThisKey="CategoryID", OtherKey="CategoryID")]
		public EntitySet<ADefHelpDesk_TaskCategory> ADefHelpDesk_TaskCategories
		{
			get
			{
				return this._ADefHelpDesk_TaskCategories;
			}
			set
			{
				this._ADefHelpDesk_TaskCategories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ADefHelpDesk_TaskCategories(ADefHelpDesk_TaskCategory entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Category = this;
		}
		
		private void detach_ADefHelpDesk_TaskCategories(ADefHelpDesk_TaskCategory entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Category = null;
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_LastSearch")]
	public partial class ADefHelpDesk_LastSearch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _UserID;
		
		private int _PortalID;
		
		private string _SearchText;
		
		private string _Status;
		
		private string _Priority;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _DueDate;
		
		private System.Nullable<int> _AssignedRoleID;
		
		private string _Categories;
		
		private System.Nullable<int> _CurrentPage;
		
		private System.Nullable<int> _PageSize;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnSearchTextChanging(string value);
    partial void OnSearchTextChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnPriorityChanging(string value);
    partial void OnPriorityChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    partial void OnAssignedRoleIDChanging(System.Nullable<int> value);
    partial void OnAssignedRoleIDChanged();
    partial void OnCategoriesChanging(string value);
    partial void OnCategoriesChanged();
    partial void OnCurrentPageChanging(System.Nullable<int> value);
    partial void OnCurrentPageChanged();
    partial void OnPageSizeChanging(System.Nullable<int> value);
    partial void OnPageSizeChanged();
    #endregion
		
		public ADefHelpDesk_LastSearch()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_SearchText", DbType="NVarChar(150)")]
		public string SearchText
		{
			get
			{
				return this._SearchText;
			}
			set
			{
				if ((this._SearchText != value))
				{
					this.OnSearchTextChanging(value);
					this.SendPropertyChanging();
					this._SearchText = value;
					this.SendPropertyChanged("SearchText");
					this.OnSearchTextChanged();
				}
			}
		}
		
		[Column(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[Column(Storage="_Priority", DbType="NVarChar(50)")]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[Column(Storage="_DueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		[Column(Storage="_AssignedRoleID", DbType="Int")]
		public System.Nullable<int> AssignedRoleID
		{
			get
			{
				return this._AssignedRoleID;
			}
			set
			{
				if ((this._AssignedRoleID != value))
				{
					this.OnAssignedRoleIDChanging(value);
					this.SendPropertyChanging();
					this._AssignedRoleID = value;
					this.SendPropertyChanged("AssignedRoleID");
					this.OnAssignedRoleIDChanged();
				}
			}
		}
		
		[Column(Storage="_Categories", DbType="NVarChar(2000)")]
		public string Categories
		{
			get
			{
				return this._Categories;
			}
			set
			{
				if ((this._Categories != value))
				{
					this.OnCategoriesChanging(value);
					this.SendPropertyChanging();
					this._Categories = value;
					this.SendPropertyChanged("Categories");
					this.OnCategoriesChanged();
				}
			}
		}
		
		[Column(Storage="_CurrentPage", DbType="Int")]
		public System.Nullable<int> CurrentPage
		{
			get
			{
				return this._CurrentPage;
			}
			set
			{
				if ((this._CurrentPage != value))
				{
					this.OnCurrentPageChanging(value);
					this.SendPropertyChanging();
					this._CurrentPage = value;
					this.SendPropertyChanged("CurrentPage");
					this.OnCurrentPageChanged();
				}
			}
		}
		
		[Column(Storage="_PageSize", DbType="Int")]
		public System.Nullable<int> PageSize
		{
			get
			{
				return this._PageSize;
			}
			set
			{
				if ((this._PageSize != value))
				{
					this.OnPageSizeChanging(value);
					this.SendPropertyChanging();
					this._PageSize = value;
					this.SendPropertyChanged("PageSize");
					this.OnPageSizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_Log")]
	public partial class ADefHelpDesk_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogID;
		
		private int _TaskID;
		
		private string _LogDescription;
		
		private System.DateTime _DateCreated;
		
		private int _UserID;
		
		private EntityRef<ADefHelpDesk_Task> _ADefHelpDesk_Task;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIDChanging(int value);
    partial void OnLogIDChanged();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnLogDescriptionChanging(string value);
    partial void OnLogDescriptionChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public ADefHelpDesk_Log()
		{
			this._ADefHelpDesk_Task = default(EntityRef<ADefHelpDesk_Task>);
			OnCreated();
		}
		
		[Column(Storage="_LogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogID
		{
			get
			{
				return this._LogID;
			}
			set
			{
				if ((this._LogID != value))
				{
					this.OnLogIDChanging(value);
					this.SendPropertyChanging();
					this._LogID = value;
					this.SendPropertyChanged("LogID");
					this.OnLogIDChanged();
				}
			}
		}
		
		[Column(Storage="_TaskID", DbType="Int NOT NULL")]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					if (this._ADefHelpDesk_Task.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_LogDescription", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string LogDescription
		{
			get
			{
				return this._LogDescription;
			}
			set
			{
				if ((this._LogDescription != value))
				{
					this.OnLogDescriptionChanging(value);
					this.SendPropertyChanging();
					this._LogDescription = value;
					this.SendPropertyChanged("LogDescription");
					this.OnLogDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_Task_ADefHelpDesk_Log", Storage="_ADefHelpDesk_Task", ThisKey="TaskID", OtherKey="TaskID", IsForeignKey=true)]
		public ADefHelpDesk_Task ADefHelpDesk_Task
		{
			get
			{
				return this._ADefHelpDesk_Task.Entity;
			}
			set
			{
				ADefHelpDesk_Task previousValue = this._ADefHelpDesk_Task.Entity;
				if (((previousValue != value) 
							|| (this._ADefHelpDesk_Task.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADefHelpDesk_Task.Entity = null;
						previousValue.ADefHelpDesk_Logs.Remove(this);
					}
					this._ADefHelpDesk_Task.Entity = value;
					if ((value != null))
					{
						value.ADefHelpDesk_Logs.Add(this);
						this._TaskID = value.TaskID;
					}
					else
					{
						this._TaskID = default(int);
					}
					this.SendPropertyChanged("ADefHelpDesk_Task");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_Roles")]
	public partial class ADefHelpDesk_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PortalID;
		
		private string _RoleName;
		
		private EntitySet<ADefHelpDesk_UserRole> _ADefHelpDesk_UserRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public ADefHelpDesk_Role()
		{
			this._ADefHelpDesk_UserRoles = new EntitySet<ADefHelpDesk_UserRole>(new Action<ADefHelpDesk_UserRole>(this.attach_ADefHelpDesk_UserRoles), new Action<ADefHelpDesk_UserRole>(this.detach_ADefHelpDesk_UserRoles));
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_RoleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_Role_ADefHelpDesk_UserRole", Storage="_ADefHelpDesk_UserRoles", ThisKey="ID", OtherKey="RoleID")]
		public EntitySet<ADefHelpDesk_UserRole> ADefHelpDesk_UserRoles
		{
			get
			{
				return this._ADefHelpDesk_UserRoles;
			}
			set
			{
				this._ADefHelpDesk_UserRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ADefHelpDesk_UserRoles(ADefHelpDesk_UserRole entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Role = this;
		}
		
		private void detach_ADefHelpDesk_UserRoles(ADefHelpDesk_UserRole entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Role = null;
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_Settings")]
	public partial class ADefHelpDesk_Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SettingID;
		
		private int _PortalID;
		
		private string _SettingName;
		
		private string _SettingValue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSettingIDChanging(int value);
    partial void OnSettingIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnSettingNameChanging(string value);
    partial void OnSettingNameChanged();
    partial void OnSettingValueChanging(string value);
    partial void OnSettingValueChanged();
    #endregion
		
		public ADefHelpDesk_Setting()
		{
			OnCreated();
		}
		
		[Column(Storage="_SettingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SettingID
		{
			get
			{
				return this._SettingID;
			}
			set
			{
				if ((this._SettingID != value))
				{
					this.OnSettingIDChanging(value);
					this.SendPropertyChanging();
					this._SettingID = value;
					this.SendPropertyChanged("SettingID");
					this.OnSettingIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_SettingName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string SettingName
		{
			get
			{
				return this._SettingName;
			}
			set
			{
				if ((this._SettingName != value))
				{
					this.OnSettingNameChanging(value);
					this.SendPropertyChanging();
					this._SettingName = value;
					this.SendPropertyChanged("SettingName");
					this.OnSettingNameChanged();
				}
			}
		}
		
		[Column(Storage="_SettingValue", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string SettingValue
		{
			get
			{
				return this._SettingValue;
			}
			set
			{
				if ((this._SettingValue != value))
				{
					this.OnSettingValueChanging(value);
					this.SendPropertyChanging();
					this._SettingValue = value;
					this.SendPropertyChanged("SettingValue");
					this.OnSettingValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_TaskAssociations")]
	public partial class ADefHelpDesk_TaskAssociation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TaskRelationID;
		
		private int _TaskID;
		
		private int _AssociatedID;
		
		private EntityRef<ADefHelpDesk_Task> _ADefHelpDesk_Task;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaskRelationIDChanging(int value);
    partial void OnTaskRelationIDChanged();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnAssociatedIDChanging(int value);
    partial void OnAssociatedIDChanged();
    #endregion
		
		public ADefHelpDesk_TaskAssociation()
		{
			this._ADefHelpDesk_Task = default(EntityRef<ADefHelpDesk_Task>);
			OnCreated();
		}
		
		[Column(Storage="_TaskRelationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TaskRelationID
		{
			get
			{
				return this._TaskRelationID;
			}
			set
			{
				if ((this._TaskRelationID != value))
				{
					this.OnTaskRelationIDChanging(value);
					this.SendPropertyChanging();
					this._TaskRelationID = value;
					this.SendPropertyChanged("TaskRelationID");
					this.OnTaskRelationIDChanged();
				}
			}
		}
		
		[Column(Storage="_TaskID", DbType="Int NOT NULL")]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					if (this._ADefHelpDesk_Task.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_AssociatedID", DbType="Int NOT NULL")]
		public int AssociatedID
		{
			get
			{
				return this._AssociatedID;
			}
			set
			{
				if ((this._AssociatedID != value))
				{
					this.OnAssociatedIDChanging(value);
					this.SendPropertyChanging();
					this._AssociatedID = value;
					this.SendPropertyChanged("AssociatedID");
					this.OnAssociatedIDChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_Task_ADefHelpDesk_TaskAssociation", Storage="_ADefHelpDesk_Task", ThisKey="TaskID", OtherKey="TaskID", IsForeignKey=true)]
		public ADefHelpDesk_Task ADefHelpDesk_Task
		{
			get
			{
				return this._ADefHelpDesk_Task.Entity;
			}
			set
			{
				ADefHelpDesk_Task previousValue = this._ADefHelpDesk_Task.Entity;
				if (((previousValue != value) 
							|| (this._ADefHelpDesk_Task.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADefHelpDesk_Task.Entity = null;
						previousValue.ADefHelpDesk_TaskAssociations.Remove(this);
					}
					this._ADefHelpDesk_Task.Entity = value;
					if ((value != null))
					{
						value.ADefHelpDesk_TaskAssociations.Add(this);
						this._TaskID = value.TaskID;
					}
					else
					{
						this._TaskID = default(int);
					}
					this.SendPropertyChanged("ADefHelpDesk_Task");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_TaskCategories")]
	public partial class ADefHelpDesk_TaskCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _TaskID;
		
		private int _CategoryID;
		
		private EntityRef<ADefHelpDesk_Category> _ADefHelpDesk_Category;
		
		private EntityRef<ADefHelpDesk_Task> _ADefHelpDesk_Task;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnCategoryIDChanging(int value);
    partial void OnCategoryIDChanged();
    #endregion
		
		public ADefHelpDesk_TaskCategory()
		{
			this._ADefHelpDesk_Category = default(EntityRef<ADefHelpDesk_Category>);
			this._ADefHelpDesk_Task = default(EntityRef<ADefHelpDesk_Task>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_TaskID", DbType="Int NOT NULL")]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					if (this._ADefHelpDesk_Task.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_CategoryID", DbType="Int NOT NULL")]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					if (this._ADefHelpDesk_Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_Category_ADefHelpDesk_TaskCategory", Storage="_ADefHelpDesk_Category", ThisKey="CategoryID", OtherKey="CategoryID", IsForeignKey=true)]
		public ADefHelpDesk_Category ADefHelpDesk_Category
		{
			get
			{
				return this._ADefHelpDesk_Category.Entity;
			}
			set
			{
				ADefHelpDesk_Category previousValue = this._ADefHelpDesk_Category.Entity;
				if (((previousValue != value) 
							|| (this._ADefHelpDesk_Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADefHelpDesk_Category.Entity = null;
						previousValue.ADefHelpDesk_TaskCategories.Remove(this);
					}
					this._ADefHelpDesk_Category.Entity = value;
					if ((value != null))
					{
						value.ADefHelpDesk_TaskCategories.Add(this);
						this._CategoryID = value.CategoryID;
					}
					else
					{
						this._CategoryID = default(int);
					}
					this.SendPropertyChanged("ADefHelpDesk_Category");
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_Task_ADefHelpDesk_TaskCategory", Storage="_ADefHelpDesk_Task", ThisKey="TaskID", OtherKey="TaskID", IsForeignKey=true)]
		public ADefHelpDesk_Task ADefHelpDesk_Task
		{
			get
			{
				return this._ADefHelpDesk_Task.Entity;
			}
			set
			{
				ADefHelpDesk_Task previousValue = this._ADefHelpDesk_Task.Entity;
				if (((previousValue != value) 
							|| (this._ADefHelpDesk_Task.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADefHelpDesk_Task.Entity = null;
						previousValue.ADefHelpDesk_TaskCategories.Remove(this);
					}
					this._ADefHelpDesk_Task.Entity = value;
					if ((value != null))
					{
						value.ADefHelpDesk_TaskCategories.Add(this);
						this._TaskID = value.TaskID;
					}
					else
					{
						this._TaskID = default(int);
					}
					this.SendPropertyChanged("ADefHelpDesk_Task");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_TaskDetails")]
	public partial class ADefHelpDesk_TaskDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DetailID;
		
		private int _TaskID;
		
		private string _DetailType;
		
		private System.DateTime _InsertDate;
		
		private int _UserID;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _StartTime;
		
		private System.Nullable<System.DateTime> _StopTime;
		
		private EntitySet<ADefHelpDesk_Attachment> _ADefHelpDesk_Attachments;
		
		private EntityRef<ADefHelpDesk_Task> _ADefHelpDesk_Task;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetailIDChanging(int value);
    partial void OnDetailIDChanged();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnDetailTypeChanging(string value);
    partial void OnDetailTypeChanged();
    partial void OnInsertDateChanging(System.DateTime value);
    partial void OnInsertDateChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnStopTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStopTimeChanged();
    #endregion
		
		public ADefHelpDesk_TaskDetail()
		{
			this._ADefHelpDesk_Attachments = new EntitySet<ADefHelpDesk_Attachment>(new Action<ADefHelpDesk_Attachment>(this.attach_ADefHelpDesk_Attachments), new Action<ADefHelpDesk_Attachment>(this.detach_ADefHelpDesk_Attachments));
			this._ADefHelpDesk_Task = default(EntityRef<ADefHelpDesk_Task>);
			OnCreated();
		}
		
		[Column(Storage="_DetailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DetailID
		{
			get
			{
				return this._DetailID;
			}
			set
			{
				if ((this._DetailID != value))
				{
					this.OnDetailIDChanging(value);
					this.SendPropertyChanging();
					this._DetailID = value;
					this.SendPropertyChanged("DetailID");
					this.OnDetailIDChanged();
				}
			}
		}
		
		[Column(Storage="_TaskID", DbType="Int NOT NULL")]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					if (this._ADefHelpDesk_Task.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_DetailType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DetailType
		{
			get
			{
				return this._DetailType;
			}
			set
			{
				if ((this._DetailType != value))
				{
					this.OnDetailTypeChanging(value);
					this.SendPropertyChanging();
					this._DetailType = value;
					this.SendPropertyChanged("DetailType");
					this.OnDetailTypeChanged();
				}
			}
		}
		
		[Column(Storage="_InsertDate", DbType="DateTime NOT NULL")]
		public System.DateTime InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[Column(Storage="_StopTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StopTime
		{
			get
			{
				return this._StopTime;
			}
			set
			{
				if ((this._StopTime != value))
				{
					this.OnStopTimeChanging(value);
					this.SendPropertyChanging();
					this._StopTime = value;
					this.SendPropertyChanged("StopTime");
					this.OnStopTimeChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_TaskDetail_ADefHelpDesk_Attachment", Storage="_ADefHelpDesk_Attachments", ThisKey="DetailID", OtherKey="DetailID")]
		public EntitySet<ADefHelpDesk_Attachment> ADefHelpDesk_Attachments
		{
			get
			{
				return this._ADefHelpDesk_Attachments;
			}
			set
			{
				this._ADefHelpDesk_Attachments.Assign(value);
			}
		}
		
		[Association(Name="ADefHelpDesk_Task_ADefHelpDesk_TaskDetail", Storage="_ADefHelpDesk_Task", ThisKey="TaskID", OtherKey="TaskID", IsForeignKey=true)]
		public ADefHelpDesk_Task ADefHelpDesk_Task
		{
			get
			{
				return this._ADefHelpDesk_Task.Entity;
			}
			set
			{
				ADefHelpDesk_Task previousValue = this._ADefHelpDesk_Task.Entity;
				if (((previousValue != value) 
							|| (this._ADefHelpDesk_Task.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADefHelpDesk_Task.Entity = null;
						previousValue.ADefHelpDesk_TaskDetails.Remove(this);
					}
					this._ADefHelpDesk_Task.Entity = value;
					if ((value != null))
					{
						value.ADefHelpDesk_TaskDetails.Add(this);
						this._TaskID = value.TaskID;
					}
					else
					{
						this._TaskID = default(int);
					}
					this.SendPropertyChanged("ADefHelpDesk_Task");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ADefHelpDesk_Attachments(ADefHelpDesk_Attachment entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_TaskDetail = this;
		}
		
		private void detach_ADefHelpDesk_Attachments(ADefHelpDesk_Attachment entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_TaskDetail = null;
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_Tasks")]
	public partial class ADefHelpDesk_Task : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TaskID;
		
		private int _PortalID;
		
		private string _Description;
		
		private string _Status;
		
		private string _Priority;
		
		private System.DateTime _CreatedDate;
		
		private System.Nullable<System.DateTime> _EstimatedStart;
		
		private System.Nullable<System.DateTime> _EstimatedCompletion;
		
		private System.Nullable<System.DateTime> _DueDate;
		
		private int _AssignedRoleID;
		
		private string _TicketPassword;
		
		private int _RequesterUserID;
		
		private string _RequesterName;
		
		private string _RequesterEmail;
		
		private string _RequesterPhone;
		
		private System.Nullable<int> _EstimatedHours;
		
		private EntitySet<ADefHelpDesk_Log> _ADefHelpDesk_Logs;
		
		private EntitySet<ADefHelpDesk_TaskAssociation> _ADefHelpDesk_TaskAssociations;
		
		private EntitySet<ADefHelpDesk_TaskCategory> _ADefHelpDesk_TaskCategories;
		
		private EntitySet<ADefHelpDesk_TaskDetail> _ADefHelpDesk_TaskDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnPriorityChanging(string value);
    partial void OnPriorityChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnEstimatedStartChanging(System.Nullable<System.DateTime> value);
    partial void OnEstimatedStartChanged();
    partial void OnEstimatedCompletionChanging(System.Nullable<System.DateTime> value);
    partial void OnEstimatedCompletionChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    partial void OnAssignedRoleIDChanging(int value);
    partial void OnAssignedRoleIDChanged();
    partial void OnTicketPasswordChanging(string value);
    partial void OnTicketPasswordChanged();
    partial void OnRequesterUserIDChanging(int value);
    partial void OnRequesterUserIDChanged();
    partial void OnRequesterNameChanging(string value);
    partial void OnRequesterNameChanged();
    partial void OnRequesterEmailChanging(string value);
    partial void OnRequesterEmailChanged();
    partial void OnRequesterPhoneChanging(string value);
    partial void OnRequesterPhoneChanged();
    partial void OnEstimatedHoursChanging(System.Nullable<int> value);
    partial void OnEstimatedHoursChanged();
    #endregion
		
		public ADefHelpDesk_Task()
		{
			this._ADefHelpDesk_Logs = new EntitySet<ADefHelpDesk_Log>(new Action<ADefHelpDesk_Log>(this.attach_ADefHelpDesk_Logs), new Action<ADefHelpDesk_Log>(this.detach_ADefHelpDesk_Logs));
			this._ADefHelpDesk_TaskAssociations = new EntitySet<ADefHelpDesk_TaskAssociation>(new Action<ADefHelpDesk_TaskAssociation>(this.attach_ADefHelpDesk_TaskAssociations), new Action<ADefHelpDesk_TaskAssociation>(this.detach_ADefHelpDesk_TaskAssociations));
			this._ADefHelpDesk_TaskCategories = new EntitySet<ADefHelpDesk_TaskCategory>(new Action<ADefHelpDesk_TaskCategory>(this.attach_ADefHelpDesk_TaskCategories), new Action<ADefHelpDesk_TaskCategory>(this.detach_ADefHelpDesk_TaskCategories));
			this._ADefHelpDesk_TaskDetails = new EntitySet<ADefHelpDesk_TaskDetail>(new Action<ADefHelpDesk_TaskDetail>(this.attach_ADefHelpDesk_TaskDetails), new Action<ADefHelpDesk_TaskDetail>(this.detach_ADefHelpDesk_TaskDetails));
			OnCreated();
		}
		
		[Column(Storage="_TaskID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_Status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[Column(Storage="_Priority", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[Column(Storage="_EstimatedStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> EstimatedStart
		{
			get
			{
				return this._EstimatedStart;
			}
			set
			{
				if ((this._EstimatedStart != value))
				{
					this.OnEstimatedStartChanging(value);
					this.SendPropertyChanging();
					this._EstimatedStart = value;
					this.SendPropertyChanged("EstimatedStart");
					this.OnEstimatedStartChanged();
				}
			}
		}
		
		[Column(Storage="_EstimatedCompletion", DbType="DateTime")]
		public System.Nullable<System.DateTime> EstimatedCompletion
		{
			get
			{
				return this._EstimatedCompletion;
			}
			set
			{
				if ((this._EstimatedCompletion != value))
				{
					this.OnEstimatedCompletionChanging(value);
					this.SendPropertyChanging();
					this._EstimatedCompletion = value;
					this.SendPropertyChanged("EstimatedCompletion");
					this.OnEstimatedCompletionChanged();
				}
			}
		}
		
		[Column(Storage="_DueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		[Column(Storage="_AssignedRoleID", DbType="Int NOT NULL")]
		public int AssignedRoleID
		{
			get
			{
				return this._AssignedRoleID;
			}
			set
			{
				if ((this._AssignedRoleID != value))
				{
					this.OnAssignedRoleIDChanging(value);
					this.SendPropertyChanging();
					this._AssignedRoleID = value;
					this.SendPropertyChanged("AssignedRoleID");
					this.OnAssignedRoleIDChanged();
				}
			}
		}
		
		[Column(Storage="_TicketPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TicketPassword
		{
			get
			{
				return this._TicketPassword;
			}
			set
			{
				if ((this._TicketPassword != value))
				{
					this.OnTicketPasswordChanging(value);
					this.SendPropertyChanging();
					this._TicketPassword = value;
					this.SendPropertyChanged("TicketPassword");
					this.OnTicketPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_RequesterUserID", DbType="Int NOT NULL")]
		public int RequesterUserID
		{
			get
			{
				return this._RequesterUserID;
			}
			set
			{
				if ((this._RequesterUserID != value))
				{
					this.OnRequesterUserIDChanging(value);
					this.SendPropertyChanging();
					this._RequesterUserID = value;
					this.SendPropertyChanged("RequesterUserID");
					this.OnRequesterUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_RequesterName", DbType="NVarChar(350)")]
		public string RequesterName
		{
			get
			{
				return this._RequesterName;
			}
			set
			{
				if ((this._RequesterName != value))
				{
					this.OnRequesterNameChanging(value);
					this.SendPropertyChanging();
					this._RequesterName = value;
					this.SendPropertyChanged("RequesterName");
					this.OnRequesterNameChanged();
				}
			}
		}
		
		[Column(Storage="_RequesterEmail", DbType="NVarChar(350)")]
		public string RequesterEmail
		{
			get
			{
				return this._RequesterEmail;
			}
			set
			{
				if ((this._RequesterEmail != value))
				{
					this.OnRequesterEmailChanging(value);
					this.SendPropertyChanging();
					this._RequesterEmail = value;
					this.SendPropertyChanged("RequesterEmail");
					this.OnRequesterEmailChanged();
				}
			}
		}
		
		[Column(Storage="_RequesterPhone", DbType="NVarChar(50)")]
		public string RequesterPhone
		{
			get
			{
				return this._RequesterPhone;
			}
			set
			{
				if ((this._RequesterPhone != value))
				{
					this.OnRequesterPhoneChanging(value);
					this.SendPropertyChanging();
					this._RequesterPhone = value;
					this.SendPropertyChanged("RequesterPhone");
					this.OnRequesterPhoneChanged();
				}
			}
		}
		
		[Column(Storage="_EstimatedHours", DbType="Int")]
		public System.Nullable<int> EstimatedHours
		{
			get
			{
				return this._EstimatedHours;
			}
			set
			{
				if ((this._EstimatedHours != value))
				{
					this.OnEstimatedHoursChanging(value);
					this.SendPropertyChanging();
					this._EstimatedHours = value;
					this.SendPropertyChanged("EstimatedHours");
					this.OnEstimatedHoursChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_Task_ADefHelpDesk_Log", Storage="_ADefHelpDesk_Logs", ThisKey="TaskID", OtherKey="TaskID")]
		public EntitySet<ADefHelpDesk_Log> ADefHelpDesk_Logs
		{
			get
			{
				return this._ADefHelpDesk_Logs;
			}
			set
			{
				this._ADefHelpDesk_Logs.Assign(value);
			}
		}
		
		[Association(Name="ADefHelpDesk_Task_ADefHelpDesk_TaskAssociation", Storage="_ADefHelpDesk_TaskAssociations", ThisKey="TaskID", OtherKey="TaskID")]
		public EntitySet<ADefHelpDesk_TaskAssociation> ADefHelpDesk_TaskAssociations
		{
			get
			{
				return this._ADefHelpDesk_TaskAssociations;
			}
			set
			{
				this._ADefHelpDesk_TaskAssociations.Assign(value);
			}
		}
		
		[Association(Name="ADefHelpDesk_Task_ADefHelpDesk_TaskCategory", Storage="_ADefHelpDesk_TaskCategories", ThisKey="TaskID", OtherKey="TaskID")]
		public EntitySet<ADefHelpDesk_TaskCategory> ADefHelpDesk_TaskCategories
		{
			get
			{
				return this._ADefHelpDesk_TaskCategories;
			}
			set
			{
				this._ADefHelpDesk_TaskCategories.Assign(value);
			}
		}
		
		[Association(Name="ADefHelpDesk_Task_ADefHelpDesk_TaskDetail", Storage="_ADefHelpDesk_TaskDetails", ThisKey="TaskID", OtherKey="TaskID")]
		public EntitySet<ADefHelpDesk_TaskDetail> ADefHelpDesk_TaskDetails
		{
			get
			{
				return this._ADefHelpDesk_TaskDetails;
			}
			set
			{
				this._ADefHelpDesk_TaskDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ADefHelpDesk_Logs(ADefHelpDesk_Log entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Task = this;
		}
		
		private void detach_ADefHelpDesk_Logs(ADefHelpDesk_Log entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Task = null;
		}
		
		private void attach_ADefHelpDesk_TaskAssociations(ADefHelpDesk_TaskAssociation entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Task = this;
		}
		
		private void detach_ADefHelpDesk_TaskAssociations(ADefHelpDesk_TaskAssociation entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Task = null;
		}
		
		private void attach_ADefHelpDesk_TaskCategories(ADefHelpDesk_TaskCategory entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Task = this;
		}
		
		private void detach_ADefHelpDesk_TaskCategories(ADefHelpDesk_TaskCategory entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Task = null;
		}
		
		private void attach_ADefHelpDesk_TaskDetails(ADefHelpDesk_TaskDetail entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Task = this;
		}
		
		private void detach_ADefHelpDesk_TaskDetails(ADefHelpDesk_TaskDetail entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_Task = null;
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_UserRoles")]
	public partial class ADefHelpDesk_UserRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserRoleID;
		
		private int _UserID;
		
		private int _RoleID;
		
		private EntityRef<ADefHelpDesk_Role> _ADefHelpDesk_Role;
		
		private EntityRef<ADefHelpDesk_User> _ADefHelpDesk_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserRoleIDChanging(int value);
    partial void OnUserRoleIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    #endregion
		
		public ADefHelpDesk_UserRole()
		{
			this._ADefHelpDesk_Role = default(EntityRef<ADefHelpDesk_Role>);
			this._ADefHelpDesk_User = default(EntityRef<ADefHelpDesk_User>);
			OnCreated();
		}
		
		[Column(Storage="_UserRoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserRoleID
		{
			get
			{
				return this._UserRoleID;
			}
			set
			{
				if ((this._UserRoleID != value))
				{
					this.OnUserRoleIDChanging(value);
					this.SendPropertyChanging();
					this._UserRoleID = value;
					this.SendPropertyChanged("UserRoleID");
					this.OnUserRoleIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._ADefHelpDesk_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					if (this._ADefHelpDesk_Role.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_Role_ADefHelpDesk_UserRole", Storage="_ADefHelpDesk_Role", ThisKey="RoleID", OtherKey="ID", IsForeignKey=true)]
		public ADefHelpDesk_Role ADefHelpDesk_Role
		{
			get
			{
				return this._ADefHelpDesk_Role.Entity;
			}
			set
			{
				ADefHelpDesk_Role previousValue = this._ADefHelpDesk_Role.Entity;
				if (((previousValue != value) 
							|| (this._ADefHelpDesk_Role.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADefHelpDesk_Role.Entity = null;
						previousValue.ADefHelpDesk_UserRoles.Remove(this);
					}
					this._ADefHelpDesk_Role.Entity = value;
					if ((value != null))
					{
						value.ADefHelpDesk_UserRoles.Add(this);
						this._RoleID = value.ID;
					}
					else
					{
						this._RoleID = default(int);
					}
					this.SendPropertyChanged("ADefHelpDesk_Role");
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_User_ADefHelpDesk_UserRole", Storage="_ADefHelpDesk_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public ADefHelpDesk_User ADefHelpDesk_User
		{
			get
			{
				return this._ADefHelpDesk_User.Entity;
			}
			set
			{
				ADefHelpDesk_User previousValue = this._ADefHelpDesk_User.Entity;
				if (((previousValue != value) 
							|| (this._ADefHelpDesk_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADefHelpDesk_User.Entity = null;
						previousValue.ADefHelpDesk_UserRoles.Remove(this);
					}
					this._ADefHelpDesk_User.Entity = value;
					if ((value != null))
					{
						value.ADefHelpDesk_UserRoles.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("ADefHelpDesk_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ADefHelpDesk_Users")]
	public partial class ADefHelpDesk_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Username;
		
		private string _FirstName;
		
		private string _LastName;
		
		private bool _IsSuperUser;
		
		private string _Email;
		
		private string _Password;
		
		private string _RIAPassword;
		
		private string _VerificationCode;
		
		private EntitySet<ADefHelpDesk_UserRole> _ADefHelpDesk_UserRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnIsSuperUserChanging(bool value);
    partial void OnIsSuperUserChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRIAPasswordChanging(string value);
    partial void OnRIAPasswordChanged();
    partial void OnVerificationCodeChanging(string value);
    partial void OnVerificationCodeChanged();
    #endregion
		
		public ADefHelpDesk_User()
		{
			this._ADefHelpDesk_UserRoles = new EntitySet<ADefHelpDesk_UserRole>(new Action<ADefHelpDesk_UserRole>(this.attach_ADefHelpDesk_UserRoles), new Action<ADefHelpDesk_UserRole>(this.detach_ADefHelpDesk_UserRoles));
			OnCreated();
		}
		
		[Column(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_Username", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[Column(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[Column(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[Column(Storage="_IsSuperUser", DbType="Bit NOT NULL")]
		public bool IsSuperUser
		{
			get
			{
				return this._IsSuperUser;
			}
			set
			{
				if ((this._IsSuperUser != value))
				{
					this.OnIsSuperUserChanging(value);
					this.SendPropertyChanging();
					this._IsSuperUser = value;
					this.SendPropertyChanged("IsSuperUser");
					this.OnIsSuperUserChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_RIAPassword", DbType="NVarChar(50)")]
		public string RIAPassword
		{
			get
			{
				return this._RIAPassword;
			}
			set
			{
				if ((this._RIAPassword != value))
				{
					this.OnRIAPasswordChanging(value);
					this.SendPropertyChanging();
					this._RIAPassword = value;
					this.SendPropertyChanged("RIAPassword");
					this.OnRIAPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_VerificationCode", DbType="NVarChar(50)")]
		public string VerificationCode
		{
			get
			{
				return this._VerificationCode;
			}
			set
			{
				if ((this._VerificationCode != value))
				{
					this.OnVerificationCodeChanging(value);
					this.SendPropertyChanging();
					this._VerificationCode = value;
					this.SendPropertyChanged("VerificationCode");
					this.OnVerificationCodeChanged();
				}
			}
		}
		
		[Association(Name="ADefHelpDesk_User_ADefHelpDesk_UserRole", Storage="_ADefHelpDesk_UserRoles", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<ADefHelpDesk_UserRole> ADefHelpDesk_UserRoles
		{
			get
			{
				return this._ADefHelpDesk_UserRoles;
			}
			set
			{
				this._ADefHelpDesk_UserRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ADefHelpDesk_UserRoles(ADefHelpDesk_UserRole entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_User = this;
		}
		
		private void detach_ADefHelpDesk_UserRoles(ADefHelpDesk_UserRole entity)
		{
			this.SendPropertyChanging();
			entity.ADefHelpDesk_User = null;
		}
	}
}
#pragma warning restore 1591
