//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace UpgradeAdvisorClient.UpgradeAdvisorWebService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpgradeItems", Namespace="http://ADefHelpDesk.com/")]
    public partial class UpgradeItems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ItemField;
        
        private string ItemDescriptionField;
        
        private string ItemDetailsField;
        
        private string ItemMethodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemDetails {
            get {
                return this.ItemDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDetailsField, value) != true)) {
                    this.ItemDetailsField = value;
                    this.RaisePropertyChanged("ItemDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemMethodName {
            get {
                return this.ItemMethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemMethodNameField, value) != true)) {
                    this.ItemMethodNameField = value;
                    this.RaisePropertyChanged("ItemMethodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ADefHelpDesk.com/", ConfigurationName="UpgradeAdvisorWebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ADefHelpDesk.com/HelloUser", ReplyAction="*")]
        System.IAsyncResult BeginHelloUser(UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserRequest request, System.AsyncCallback callback, object asyncState);
        
        UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserResponse EndHelloUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ADefHelpDesk.com/CurrentVersionOfADefHelpDeskUpgradeAdvisor", ReplyAction="*")]
        System.IAsyncResult BeginCurrentVersionOfADefHelpDeskUpgradeAdvisor(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorRequest request, System.AsyncCallback callback, object asyncState);
        
        UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse EndCurrentVersionOfADefHelpDeskUpgradeAdvisor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ADefHelpDesk.com/GetUpgradeItems", ReplyAction="*")]
        System.IAsyncResult BeginGetUpgradeItems(UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsRequest request, System.AsyncCallback callback, object asyncState);
        
        UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsResponse EndGetUpgradeItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ADefHelpDesk.com/CurrentVersionOfADefHelpDesk", ReplyAction="*")]
        System.IAsyncResult BeginCurrentVersionOfADefHelpDesk(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskRequest request, System.AsyncCallback callback, object asyncState);
        
        UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskResponse EndCurrentVersionOfADefHelpDesk(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ADefHelpDesk.com/ADefHelpDeskLastSearchCurrentPagePresent", ReplyAction="*")]
        System.IAsyncResult BeginADefHelpDeskLastSearchCurrentPagePresent(UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentRequest request, System.AsyncCallback callback, object asyncState);
        
        UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentResponse EndADefHelpDeskLastSearchCurrentPagePresent(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloUser", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserRequestBody Body;
        
        public HelloUserRequest() {
        }
        
        public HelloUserRequest(UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class HelloUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ModuleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public HelloUserRequestBody() {
        }
        
        public HelloUserRequestBody(int PortalID, int ModuleId, int UserID, string Password) {
            this.PortalID = PortalID;
            this.ModuleId = ModuleId;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloUserResponse", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserResponseBody Body;
        
        public HelloUserResponse() {
        }
        
        public HelloUserResponse(UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class HelloUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloUserResult;
        
        public HelloUserResponseBody() {
        }
        
        public HelloUserResponseBody(string HelloUserResult) {
            this.HelloUserResult = HelloUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentVersionOfADefHelpDeskUpgradeAdvisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentVersionOfADefHelpDeskUpgradeAdvisor", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorRequestBody Body;
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorRequest() {
        }
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorRequest(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class CurrentVersionOfADefHelpDeskUpgradeAdvisorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ModuleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorRequestBody() {
        }
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorRequestBody(int PortalID, int ModuleId, int UserID, string Password) {
            this.PortalID = PortalID;
            this.ModuleId = ModuleId;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorResponseBody Body;
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse() {
        }
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class CurrentVersionOfADefHelpDeskUpgradeAdvisorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrentVersionOfADefHelpDeskUpgradeAdvisorResult;
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorResponseBody() {
        }
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorResponseBody(string CurrentVersionOfADefHelpDeskUpgradeAdvisorResult) {
            this.CurrentVersionOfADefHelpDeskUpgradeAdvisorResult = CurrentVersionOfADefHelpDeskUpgradeAdvisorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpgradeItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpgradeItems", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsRequestBody Body;
        
        public GetUpgradeItemsRequest() {
        }
        
        public GetUpgradeItemsRequest(UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class GetUpgradeItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ModuleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strCurrentVersion;
        
        public GetUpgradeItemsRequestBody() {
        }
        
        public GetUpgradeItemsRequestBody(int PortalID, int ModuleId, int UserID, string Password, string strCurrentVersion) {
            this.PortalID = PortalID;
            this.ModuleId = ModuleId;
            this.UserID = UserID;
            this.Password = Password;
            this.strCurrentVersion = strCurrentVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpgradeItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpgradeItemsResponse", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsResponseBody Body;
        
        public GetUpgradeItemsResponse() {
        }
        
        public GetUpgradeItemsResponse(UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class GetUpgradeItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<UpgradeAdvisorClient.UpgradeAdvisorWebService.UpgradeItems> GetUpgradeItemsResult;
        
        public GetUpgradeItemsResponseBody() {
        }
        
        public GetUpgradeItemsResponseBody(System.Collections.Generic.List<UpgradeAdvisorClient.UpgradeAdvisorWebService.UpgradeItems> GetUpgradeItemsResult) {
            this.GetUpgradeItemsResult = GetUpgradeItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentVersionOfADefHelpDeskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentVersionOfADefHelpDesk", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskRequestBody Body;
        
        public CurrentVersionOfADefHelpDeskRequest() {
        }
        
        public CurrentVersionOfADefHelpDeskRequest(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class CurrentVersionOfADefHelpDeskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ModuleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public CurrentVersionOfADefHelpDeskRequestBody() {
        }
        
        public CurrentVersionOfADefHelpDeskRequestBody(int PortalID, int ModuleId, int UserID, string Password) {
            this.PortalID = PortalID;
            this.ModuleId = ModuleId;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentVersionOfADefHelpDeskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentVersionOfADefHelpDeskResponse", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskResponseBody Body;
        
        public CurrentVersionOfADefHelpDeskResponse() {
        }
        
        public CurrentVersionOfADefHelpDeskResponse(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class CurrentVersionOfADefHelpDeskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrentVersionOfADefHelpDeskResult;
        
        public CurrentVersionOfADefHelpDeskResponseBody() {
        }
        
        public CurrentVersionOfADefHelpDeskResponseBody(string CurrentVersionOfADefHelpDeskResult) {
            this.CurrentVersionOfADefHelpDeskResult = CurrentVersionOfADefHelpDeskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADefHelpDeskLastSearchCurrentPagePresentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADefHelpDeskLastSearchCurrentPagePresent", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentRequestBody Body;
        
        public ADefHelpDeskLastSearchCurrentPagePresentRequest() {
        }
        
        public ADefHelpDeskLastSearchCurrentPagePresentRequest(UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class ADefHelpDeskLastSearchCurrentPagePresentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ModuleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public ADefHelpDeskLastSearchCurrentPagePresentRequestBody() {
        }
        
        public ADefHelpDeskLastSearchCurrentPagePresentRequestBody(int PortalID, int ModuleId, int UserID, string Password) {
            this.PortalID = PortalID;
            this.ModuleId = ModuleId;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADefHelpDeskLastSearchCurrentPagePresentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADefHelpDeskLastSearchCurrentPagePresentResponse", Namespace="http://ADefHelpDesk.com/", Order=0)]
        public UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentResponseBody Body;
        
        public ADefHelpDeskLastSearchCurrentPagePresentResponse() {
        }
        
        public ADefHelpDeskLastSearchCurrentPagePresentResponse(UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ADefHelpDesk.com/")]
    public partial class ADefHelpDeskLastSearchCurrentPagePresentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ADefHelpDeskLastSearchCurrentPagePresentResult;
        
        public ADefHelpDeskLastSearchCurrentPagePresentResponseBody() {
        }
        
        public ADefHelpDeskLastSearchCurrentPagePresentResponseBody(bool ADefHelpDeskLastSearchCurrentPagePresentResult) {
            this.ADefHelpDeskLastSearchCurrentPagePresentResult = ADefHelpDeskLastSearchCurrentPagePresentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WebServiceSoapChannel : UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class HelloUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CurrentVersionOfADefHelpDeskUpgradeAdvisorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CurrentVersionOfADefHelpDeskUpgradeAdvisorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetUpgradeItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUpgradeItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<UpgradeAdvisorClient.UpgradeAdvisorWebService.UpgradeItems> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<UpgradeAdvisorClient.UpgradeAdvisorWebService.UpgradeItems>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CurrentVersionOfADefHelpDeskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CurrentVersionOfADefHelpDeskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ADefHelpDeskLastSearchCurrentPagePresentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ADefHelpDeskLastSearchCurrentPagePresentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap>, UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap {
        
        private BeginOperationDelegate onBeginHelloUserDelegate;
        
        private EndOperationDelegate onEndHelloUserDelegate;
        
        private System.Threading.SendOrPostCallback onHelloUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginCurrentVersionOfADefHelpDeskUpgradeAdvisorDelegate;
        
        private EndOperationDelegate onEndCurrentVersionOfADefHelpDeskUpgradeAdvisorDelegate;
        
        private System.Threading.SendOrPostCallback onCurrentVersionOfADefHelpDeskUpgradeAdvisorCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUpgradeItemsDelegate;
        
        private EndOperationDelegate onEndGetUpgradeItemsDelegate;
        
        private System.Threading.SendOrPostCallback onGetUpgradeItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginCurrentVersionOfADefHelpDeskDelegate;
        
        private EndOperationDelegate onEndCurrentVersionOfADefHelpDeskDelegate;
        
        private System.Threading.SendOrPostCallback onCurrentVersionOfADefHelpDeskCompletedDelegate;
        
        private BeginOperationDelegate onBeginADefHelpDeskLastSearchCurrentPagePresentDelegate;
        
        private EndOperationDelegate onEndADefHelpDeskLastSearchCurrentPagePresentDelegate;
        
        private System.Threading.SendOrPostCallback onADefHelpDeskLastSearchCurrentPagePresentCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloUserCompletedEventArgs> HelloUserCompleted;
        
        public event System.EventHandler<CurrentVersionOfADefHelpDeskUpgradeAdvisorCompletedEventArgs> CurrentVersionOfADefHelpDeskUpgradeAdvisorCompleted;
        
        public event System.EventHandler<GetUpgradeItemsCompletedEventArgs> GetUpgradeItemsCompleted;
        
        public event System.EventHandler<CurrentVersionOfADefHelpDeskCompletedEventArgs> CurrentVersionOfADefHelpDeskCompleted;
        
        public event System.EventHandler<ADefHelpDeskLastSearchCurrentPagePresentCompletedEventArgs> ADefHelpDeskLastSearchCurrentPagePresentCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.BeginHelloUser(UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloUser(int PortalID, int ModuleId, int UserID, string Password, System.AsyncCallback callback, object asyncState) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserRequest inValue = new UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserRequest();
            inValue.Body = new UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserRequestBody();
            inValue.Body.PortalID = PortalID;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.UserID = UserID;
            inValue.Body.Password = Password;
            return ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).BeginHelloUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserResponse UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.EndHelloUser(System.IAsyncResult result) {
            return base.Channel.EndHelloUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloUser(System.IAsyncResult result) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserResponse retVal = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).EndHelloUser(result);
            return retVal.Body.HelloUserResult;
        }
        
        private System.IAsyncResult OnBeginHelloUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int PortalID = ((int)(inValues[0]));
            int ModuleId = ((int)(inValues[1]));
            int UserID = ((int)(inValues[2]));
            string Password = ((string)(inValues[3]));
            return this.BeginHelloUser(PortalID, ModuleId, UserID, Password, callback, asyncState);
        }
        
        private object[] OnEndHelloUser(System.IAsyncResult result) {
            string retVal = this.EndHelloUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloUserCompleted(object state) {
            if ((this.HelloUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloUserCompleted(this, new HelloUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloUserAsync(int PortalID, int ModuleId, int UserID, string Password) {
            this.HelloUserAsync(PortalID, ModuleId, UserID, Password, null);
        }
        
        public void HelloUserAsync(int PortalID, int ModuleId, int UserID, string Password, object userState) {
            if ((this.onBeginHelloUserDelegate == null)) {
                this.onBeginHelloUserDelegate = new BeginOperationDelegate(this.OnBeginHelloUser);
            }
            if ((this.onEndHelloUserDelegate == null)) {
                this.onEndHelloUserDelegate = new EndOperationDelegate(this.OnEndHelloUser);
            }
            if ((this.onHelloUserCompletedDelegate == null)) {
                this.onHelloUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloUserCompleted);
            }
            base.InvokeAsync(this.onBeginHelloUserDelegate, new object[] {
                        PortalID,
                        ModuleId,
                        UserID,
                        Password}, this.onEndHelloUserDelegate, this.onHelloUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.BeginCurrentVersionOfADefHelpDeskUpgradeAdvisor(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCurrentVersionOfADefHelpDeskUpgradeAdvisor(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCurrentVersionOfADefHelpDeskUpgradeAdvisor(int PortalID, int ModuleId, int UserID, string Password, System.AsyncCallback callback, object asyncState) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorRequest inValue = new UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorRequest();
            inValue.Body = new UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorRequestBody();
            inValue.Body.PortalID = PortalID;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.UserID = UserID;
            inValue.Body.Password = Password;
            return ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).BeginCurrentVersionOfADefHelpDeskUpgradeAdvisor(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.EndCurrentVersionOfADefHelpDeskUpgradeAdvisor(System.IAsyncResult result) {
            return base.Channel.EndCurrentVersionOfADefHelpDeskUpgradeAdvisor(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndCurrentVersionOfADefHelpDeskUpgradeAdvisor(System.IAsyncResult result) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse retVal = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).EndCurrentVersionOfADefHelpDeskUpgradeAdvisor(result);
            return retVal.Body.CurrentVersionOfADefHelpDeskUpgradeAdvisorResult;
        }
        
        private System.IAsyncResult OnBeginCurrentVersionOfADefHelpDeskUpgradeAdvisor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int PortalID = ((int)(inValues[0]));
            int ModuleId = ((int)(inValues[1]));
            int UserID = ((int)(inValues[2]));
            string Password = ((string)(inValues[3]));
            return this.BeginCurrentVersionOfADefHelpDeskUpgradeAdvisor(PortalID, ModuleId, UserID, Password, callback, asyncState);
        }
        
        private object[] OnEndCurrentVersionOfADefHelpDeskUpgradeAdvisor(System.IAsyncResult result) {
            string retVal = this.EndCurrentVersionOfADefHelpDeskUpgradeAdvisor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCurrentVersionOfADefHelpDeskUpgradeAdvisorCompleted(object state) {
            if ((this.CurrentVersionOfADefHelpDeskUpgradeAdvisorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CurrentVersionOfADefHelpDeskUpgradeAdvisorCompleted(this, new CurrentVersionOfADefHelpDeskUpgradeAdvisorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CurrentVersionOfADefHelpDeskUpgradeAdvisorAsync(int PortalID, int ModuleId, int UserID, string Password) {
            this.CurrentVersionOfADefHelpDeskUpgradeAdvisorAsync(PortalID, ModuleId, UserID, Password, null);
        }
        
        public void CurrentVersionOfADefHelpDeskUpgradeAdvisorAsync(int PortalID, int ModuleId, int UserID, string Password, object userState) {
            if ((this.onBeginCurrentVersionOfADefHelpDeskUpgradeAdvisorDelegate == null)) {
                this.onBeginCurrentVersionOfADefHelpDeskUpgradeAdvisorDelegate = new BeginOperationDelegate(this.OnBeginCurrentVersionOfADefHelpDeskUpgradeAdvisor);
            }
            if ((this.onEndCurrentVersionOfADefHelpDeskUpgradeAdvisorDelegate == null)) {
                this.onEndCurrentVersionOfADefHelpDeskUpgradeAdvisorDelegate = new EndOperationDelegate(this.OnEndCurrentVersionOfADefHelpDeskUpgradeAdvisor);
            }
            if ((this.onCurrentVersionOfADefHelpDeskUpgradeAdvisorCompletedDelegate == null)) {
                this.onCurrentVersionOfADefHelpDeskUpgradeAdvisorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCurrentVersionOfADefHelpDeskUpgradeAdvisorCompleted);
            }
            base.InvokeAsync(this.onBeginCurrentVersionOfADefHelpDeskUpgradeAdvisorDelegate, new object[] {
                        PortalID,
                        ModuleId,
                        UserID,
                        Password}, this.onEndCurrentVersionOfADefHelpDeskUpgradeAdvisorDelegate, this.onCurrentVersionOfADefHelpDeskUpgradeAdvisorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.BeginGetUpgradeItems(UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUpgradeItems(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetUpgradeItems(int PortalID, int ModuleId, int UserID, string Password, string strCurrentVersion, System.AsyncCallback callback, object asyncState) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsRequest inValue = new UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsRequest();
            inValue.Body = new UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsRequestBody();
            inValue.Body.PortalID = PortalID;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.UserID = UserID;
            inValue.Body.Password = Password;
            inValue.Body.strCurrentVersion = strCurrentVersion;
            return ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).BeginGetUpgradeItems(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsResponse UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.EndGetUpgradeItems(System.IAsyncResult result) {
            return base.Channel.EndGetUpgradeItems(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.Generic.List<UpgradeAdvisorClient.UpgradeAdvisorWebService.UpgradeItems> EndGetUpgradeItems(System.IAsyncResult result) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsResponse retVal = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).EndGetUpgradeItems(result);
            return retVal.Body.GetUpgradeItemsResult;
        }
        
        private System.IAsyncResult OnBeginGetUpgradeItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int PortalID = ((int)(inValues[0]));
            int ModuleId = ((int)(inValues[1]));
            int UserID = ((int)(inValues[2]));
            string Password = ((string)(inValues[3]));
            string strCurrentVersion = ((string)(inValues[4]));
            return this.BeginGetUpgradeItems(PortalID, ModuleId, UserID, Password, strCurrentVersion, callback, asyncState);
        }
        
        private object[] OnEndGetUpgradeItems(System.IAsyncResult result) {
            System.Collections.Generic.List<UpgradeAdvisorClient.UpgradeAdvisorWebService.UpgradeItems> retVal = this.EndGetUpgradeItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUpgradeItemsCompleted(object state) {
            if ((this.GetUpgradeItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUpgradeItemsCompleted(this, new GetUpgradeItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUpgradeItemsAsync(int PortalID, int ModuleId, int UserID, string Password, string strCurrentVersion) {
            this.GetUpgradeItemsAsync(PortalID, ModuleId, UserID, Password, strCurrentVersion, null);
        }
        
        public void GetUpgradeItemsAsync(int PortalID, int ModuleId, int UserID, string Password, string strCurrentVersion, object userState) {
            if ((this.onBeginGetUpgradeItemsDelegate == null)) {
                this.onBeginGetUpgradeItemsDelegate = new BeginOperationDelegate(this.OnBeginGetUpgradeItems);
            }
            if ((this.onEndGetUpgradeItemsDelegate == null)) {
                this.onEndGetUpgradeItemsDelegate = new EndOperationDelegate(this.OnEndGetUpgradeItems);
            }
            if ((this.onGetUpgradeItemsCompletedDelegate == null)) {
                this.onGetUpgradeItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUpgradeItemsCompleted);
            }
            base.InvokeAsync(this.onBeginGetUpgradeItemsDelegate, new object[] {
                        PortalID,
                        ModuleId,
                        UserID,
                        Password,
                        strCurrentVersion}, this.onEndGetUpgradeItemsDelegate, this.onGetUpgradeItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.BeginCurrentVersionOfADefHelpDesk(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCurrentVersionOfADefHelpDesk(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCurrentVersionOfADefHelpDesk(int PortalID, int ModuleId, int UserID, string Password, System.AsyncCallback callback, object asyncState) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskRequest inValue = new UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskRequest();
            inValue.Body = new UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskRequestBody();
            inValue.Body.PortalID = PortalID;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.UserID = UserID;
            inValue.Body.Password = Password;
            return ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).BeginCurrentVersionOfADefHelpDesk(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskResponse UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.EndCurrentVersionOfADefHelpDesk(System.IAsyncResult result) {
            return base.Channel.EndCurrentVersionOfADefHelpDesk(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndCurrentVersionOfADefHelpDesk(System.IAsyncResult result) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskResponse retVal = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).EndCurrentVersionOfADefHelpDesk(result);
            return retVal.Body.CurrentVersionOfADefHelpDeskResult;
        }
        
        private System.IAsyncResult OnBeginCurrentVersionOfADefHelpDesk(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int PortalID = ((int)(inValues[0]));
            int ModuleId = ((int)(inValues[1]));
            int UserID = ((int)(inValues[2]));
            string Password = ((string)(inValues[3]));
            return this.BeginCurrentVersionOfADefHelpDesk(PortalID, ModuleId, UserID, Password, callback, asyncState);
        }
        
        private object[] OnEndCurrentVersionOfADefHelpDesk(System.IAsyncResult result) {
            string retVal = this.EndCurrentVersionOfADefHelpDesk(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCurrentVersionOfADefHelpDeskCompleted(object state) {
            if ((this.CurrentVersionOfADefHelpDeskCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CurrentVersionOfADefHelpDeskCompleted(this, new CurrentVersionOfADefHelpDeskCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CurrentVersionOfADefHelpDeskAsync(int PortalID, int ModuleId, int UserID, string Password) {
            this.CurrentVersionOfADefHelpDeskAsync(PortalID, ModuleId, UserID, Password, null);
        }
        
        public void CurrentVersionOfADefHelpDeskAsync(int PortalID, int ModuleId, int UserID, string Password, object userState) {
            if ((this.onBeginCurrentVersionOfADefHelpDeskDelegate == null)) {
                this.onBeginCurrentVersionOfADefHelpDeskDelegate = new BeginOperationDelegate(this.OnBeginCurrentVersionOfADefHelpDesk);
            }
            if ((this.onEndCurrentVersionOfADefHelpDeskDelegate == null)) {
                this.onEndCurrentVersionOfADefHelpDeskDelegate = new EndOperationDelegate(this.OnEndCurrentVersionOfADefHelpDesk);
            }
            if ((this.onCurrentVersionOfADefHelpDeskCompletedDelegate == null)) {
                this.onCurrentVersionOfADefHelpDeskCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCurrentVersionOfADefHelpDeskCompleted);
            }
            base.InvokeAsync(this.onBeginCurrentVersionOfADefHelpDeskDelegate, new object[] {
                        PortalID,
                        ModuleId,
                        UserID,
                        Password}, this.onEndCurrentVersionOfADefHelpDeskDelegate, this.onCurrentVersionOfADefHelpDeskCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.BeginADefHelpDeskLastSearchCurrentPagePresent(UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginADefHelpDeskLastSearchCurrentPagePresent(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginADefHelpDeskLastSearchCurrentPagePresent(int PortalID, int ModuleId, int UserID, string Password, System.AsyncCallback callback, object asyncState) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentRequest inValue = new UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentRequest();
            inValue.Body = new UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentRequestBody();
            inValue.Body.PortalID = PortalID;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.UserID = UserID;
            inValue.Body.Password = Password;
            return ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).BeginADefHelpDeskLastSearchCurrentPagePresent(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentResponse UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap.EndADefHelpDeskLastSearchCurrentPagePresent(System.IAsyncResult result) {
            return base.Channel.EndADefHelpDeskLastSearchCurrentPagePresent(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndADefHelpDeskLastSearchCurrentPagePresent(System.IAsyncResult result) {
            UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentResponse retVal = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap)(this)).EndADefHelpDeskLastSearchCurrentPagePresent(result);
            return retVal.Body.ADefHelpDeskLastSearchCurrentPagePresentResult;
        }
        
        private System.IAsyncResult OnBeginADefHelpDeskLastSearchCurrentPagePresent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int PortalID = ((int)(inValues[0]));
            int ModuleId = ((int)(inValues[1]));
            int UserID = ((int)(inValues[2]));
            string Password = ((string)(inValues[3]));
            return this.BeginADefHelpDeskLastSearchCurrentPagePresent(PortalID, ModuleId, UserID, Password, callback, asyncState);
        }
        
        private object[] OnEndADefHelpDeskLastSearchCurrentPagePresent(System.IAsyncResult result) {
            bool retVal = this.EndADefHelpDeskLastSearchCurrentPagePresent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnADefHelpDeskLastSearchCurrentPagePresentCompleted(object state) {
            if ((this.ADefHelpDeskLastSearchCurrentPagePresentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ADefHelpDeskLastSearchCurrentPagePresentCompleted(this, new ADefHelpDeskLastSearchCurrentPagePresentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ADefHelpDeskLastSearchCurrentPagePresentAsync(int PortalID, int ModuleId, int UserID, string Password) {
            this.ADefHelpDeskLastSearchCurrentPagePresentAsync(PortalID, ModuleId, UserID, Password, null);
        }
        
        public void ADefHelpDeskLastSearchCurrentPagePresentAsync(int PortalID, int ModuleId, int UserID, string Password, object userState) {
            if ((this.onBeginADefHelpDeskLastSearchCurrentPagePresentDelegate == null)) {
                this.onBeginADefHelpDeskLastSearchCurrentPagePresentDelegate = new BeginOperationDelegate(this.OnBeginADefHelpDeskLastSearchCurrentPagePresent);
            }
            if ((this.onEndADefHelpDeskLastSearchCurrentPagePresentDelegate == null)) {
                this.onEndADefHelpDeskLastSearchCurrentPagePresentDelegate = new EndOperationDelegate(this.OnEndADefHelpDeskLastSearchCurrentPagePresent);
            }
            if ((this.onADefHelpDeskLastSearchCurrentPagePresentCompletedDelegate == null)) {
                this.onADefHelpDeskLastSearchCurrentPagePresentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnADefHelpDeskLastSearchCurrentPagePresentCompleted);
            }
            base.InvokeAsync(this.onBeginADefHelpDeskLastSearchCurrentPagePresentDelegate, new object[] {
                        PortalID,
                        ModuleId,
                        UserID,
                        Password}, this.onEndADefHelpDeskLastSearchCurrentPagePresentDelegate, this.onADefHelpDeskLastSearchCurrentPagePresentCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap CreateChannel() {
            return new WebServiceSoapClientChannel(this);
        }
        
        private class WebServiceSoapClientChannel : ChannelBase<UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap>, UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap {
            
            public WebServiceSoapClientChannel(System.ServiceModel.ClientBase<UpgradeAdvisorClient.UpgradeAdvisorWebService.WebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloUser(UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloUser", _args, callback, asyncState);
                return _result;
            }
            
            public UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserResponse EndHelloUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserResponse _result = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.HelloUserResponse)(base.EndInvoke("HelloUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCurrentVersionOfADefHelpDeskUpgradeAdvisor(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CurrentVersionOfADefHelpDeskUpgradeAdvisor", _args, callback, asyncState);
                return _result;
            }
            
            public UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse EndCurrentVersionOfADefHelpDeskUpgradeAdvisor(System.IAsyncResult result) {
                object[] _args = new object[0];
                UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse _result = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskUpgradeAdvisorResponse)(base.EndInvoke("CurrentVersionOfADefHelpDeskUpgradeAdvisor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUpgradeItems(UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetUpgradeItems", _args, callback, asyncState);
                return _result;
            }
            
            public UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsResponse EndGetUpgradeItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsResponse _result = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.GetUpgradeItemsResponse)(base.EndInvoke("GetUpgradeItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCurrentVersionOfADefHelpDesk(UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CurrentVersionOfADefHelpDesk", _args, callback, asyncState);
                return _result;
            }
            
            public UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskResponse EndCurrentVersionOfADefHelpDesk(System.IAsyncResult result) {
                object[] _args = new object[0];
                UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskResponse _result = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.CurrentVersionOfADefHelpDeskResponse)(base.EndInvoke("CurrentVersionOfADefHelpDesk", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginADefHelpDeskLastSearchCurrentPagePresent(UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ADefHelpDeskLastSearchCurrentPagePresent", _args, callback, asyncState);
                return _result;
            }
            
            public UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentResponse EndADefHelpDeskLastSearchCurrentPagePresent(System.IAsyncResult result) {
                object[] _args = new object[0];
                UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentResponse _result = ((UpgradeAdvisorClient.UpgradeAdvisorWebService.ADefHelpDeskLastSearchCurrentPagePresentResponse)(base.EndInvoke("ADefHelpDeskLastSearchCurrentPagePresent", _args, result)));
                return _result;
            }
        }
    }
}
